
services:
  odoo:
    image: apik/odoo:18.0-20250901-enterprise
    command: odoo --dev=reload
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
      - SMTP_HOST=maildev
      - SMTP_PORT=1025
    volumes:
      - ./config:/etc/odoo:rw
      - ./extra-addons:/mnt/extra-addons:rw
      - odoo-data:/var/lib/odoo
  postgres:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
    depends_on:
      - odoo
    environment:
      - TZ=Europe/Paris
  sftp:
      image: atmoz/sftp
      volumes:
          - ./sftp:/home/user/upload
      ports:
          - "2222:22"
      command: user:password:1001
volumes:
  odoo-data:
  postgres-data: